### ISSUE TITLE
[Bug]: Diagonal Fences prevent Immersive Engineering multiblocks to form

### ISSUE THREAD

**Issue by dandalous** [Fuzss/diagonalfences#12]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.2

### Notes (Required)

This isn't a bug so much as it is a call for help on how to add the tag "diagonalfences:non_diagonal_fences" to Immersive Engineering's fences (immersiveengineering:treated_fence) so that multiblocks can form properly. (They form correctly without the mod installed). Or maybe have a blacklist in Diagonal Fences' config?
![2023-12-07_03 22 54](https://github.com/Fuzss/diagonalfences/assets/125793933/526a0950-104c-404a-afc4-0460a4f5fde9)

**Comment by Fuzss** [comment]
Fixed in v8.1.3.

**Comment by ASpieler** [comment]
this issue is still present
DF: v8.1.3-1.20.1-Forge
IE: 1.20.1-10.0.0-169
